// Shrinks the product photography in public/ and emits blur placeholders.
// Originals are copied to assets-original/ (gitignored) before anything is
// overwritten, so this can always be re-run from the masters.
//
// Run: node scripts/optimize-images.js
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const PUBLIC = path.join(ROOT, "public");
const BACKUP = path.join(ROOT, "assets-original");

// Nothing on the site displays a product wider than ~800 CSS px; 1200 covers
// retina with room to spare.
const MAX_EDGE = 1200;
const HERO_EDGE = 1600;

const kb = (n) => `${Math.round(n / 1024)}KB`;

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) return walk(full);
    return /\.(png|jpe?g)$/i.test(e.name) ? [full] : [];
  });
}

function backup(file) {
  const rel = path.relative(PUBLIC, file);
  const dest = path.join(BACKUP, rel);
  if (fs.existsSync(dest)) return; // keep the first master we ever saw
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(file, dest);
}

async function optimise(file) {
  const before = fs.statSync(file).size;
  const meta = await sharp(file).metadata();
  const maxEdge = file.endsWith("hero.jpg") ? HERO_EDGE : MAX_EDGE;
  const tooBig = Math.max(meta.width ?? 0, meta.height ?? 0) > maxEdge;

  // A PNG without alpha is a photograph stored losslessly — JPEG is far smaller
  const isPhotoPng = file.endsWith(".png") && !meta.hasAlpha;
  const outFile = isPhotoPng ? file.replace(/\.png$/, ".jpg") : file;

  backup(file);

  let img = sharp(file);
  if (tooBig) img = img.resize(maxEdge, maxEdge, { fit: "inside", withoutEnlargement: true });

  if (outFile.endsWith(".png")) {
    img = img.png({ compressionLevel: 9, effort: 10, palette: true });
  } else {
    img = img.jpeg({ quality: file.endsWith("hero.jpg") ? 78 : 82, progressive: true, mozjpeg: true });
  }

  const buf = await img.toBuffer();
  // Only keep the new file if it actually saves bytes (or changes format)
  if (buf.length < before || outFile !== file) {
    fs.writeFileSync(outFile, buf);
    if (outFile !== file) fs.unlinkSync(file);
  }
  const after = fs.statSync(outFile).size;
  return { outFile, before, after, converted: outFile !== file };
}

async function blurFor(file) {
  const buf = await sharp(file)
    .resize(12, 12, { fit: "inside" })
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

(async () => {
  const files = walk(path.join(PUBLIC, "photos"));
  let before = 0;
  let after = 0;
  const renames = [];

  for (const f of files) {
    const r = await optimise(f);
    before += r.before;
    after += r.after;
    renames.push([f, r.outFile, r]);
    const tag = r.converted ? " → jpg" : "";
    console.log(`${path.relative(PUBLIC, r.outFile).padEnd(46)} ${kb(r.before)} → ${kb(r.after)}${tag}`);
  }

  // Blur placeholders for the images used above the fold
  const blurTargets = [
    "photos/hero.jpg",
    ...renames
      .map(([, out]) => path.relative(PUBLIC, out))
      .filter((p) => p.split("/").length === 2), // category folders only
  ];
  const blur = {};
  for (const rel of [...new Set(blurTargets)]) {
    const full = path.join(PUBLIC, rel);
    if (fs.existsSync(full)) blur[`/${rel}`] = await blurFor(full);
  }

  fs.writeFileSync(
    path.join(ROOT, "src/data/blur.ts"),
    `// Generated by scripts/optimize-images.js — tiny base64 previews shown\n` +
      `// while the full image loads. Re-run the script after changing photos.\n` +
      `export const blurDataUrls: Record<string, string> = ${JSON.stringify(blur, null, 2)};\n\n` +
      `export const blurFor = (src: string) => blurDataUrls[src];\n`,
  );

  console.log(
    `\ntotal ${kb(before)} → ${kb(after)}  (saved ${kb(before - after)}, ${Math.round((1 - after / before) * 100)}%)`,
  );
  console.log(`blur placeholders: ${Object.keys(blur).length} → src/data/blur.ts`);
  const converted = renames.filter(([, , r]) => r.converted);
  if (converted.length) {
    console.log("\nRenamed to .jpg — update these paths in code:");
    for (const [from, to] of converted) {
      console.log(`  /${path.relative(PUBLIC, from)}  →  /${path.relative(PUBLIC, to)}`);
    }
  }
})().catch((e) => {
  console.error("ERR", e.message);
  process.exit(1);
});
